import type { FieldTask } from "./types";

export const SAMPLE_TASKS: FieldTask[] = [
  {
    id: "T-118",
    type: "fm",
    title: "วิทยุชุมชนบ้านบึง",
    province: "Chonburi",
    district: "Ban Bueng",
    status: "in_progress",
    ranking: null,
    lat: 13.3131,
    long: 101.2541,
    etaMinutes: 12,
    distanceKm: 4.8,
    freq: 96.75,
    note: "Inspection pending — operator contacted",
  },
  {
    id: "T-119",
    type: "interference",
    title: "AWN-112 · Sector B",
    province: "Chonburi",
    district: "Sriracha",
    status: "pending",
    ranking: "critical",
    lat: 13.1761,
    long: 100.9321,
    etaMinutes: 28,
    distanceKm: 14.2,
    direction: 215,
    note: "N/I spike reported overnight",
  },
  {
    id: "T-120",
    type: "fm",
    title: "คลื่นเรดิโอ 98.25",
    province: "Rayong",
    district: "Klaeng",
    status: "pending",
    ranking: null,
    lat: 12.777,
    long: 101.6495,
    etaMinutes: 47,
    distanceKm: 23.6,
    freq: 98.25,
  },
  {
    id: "T-121",
    type: "interference",
    title: "AWN-087 · Sector A",
    province: "Rayong",
    district: "Muang Rayong",
    status: "pending",
    ranking: "major",
    lat: 12.6839,
    long: 101.2377,
    etaMinutes: 55,
    distanceKm: 31.4,
    direction: 45,
  },
  {
    id: "T-122",
    type: "fm",
    title: "ร่วมใจเรดิโอ 100.50",
    province: "Chonburi",
    district: "Phan Thong",
    status: "inspected",
    ranking: null,
    lat: 13.4771,
    long: 101.0255,
    etaMinutes: 0,
    distanceKm: 0,
    freq: 100.5,
  },
  {
    id: "T-123",
    type: "interference",
    title: "AWN-204 · Sector C",
    province: "Rayong",
    district: "Ban Chang",
    status: "law_sent",
    ranking: "minor",
    lat: 12.72,
    long: 101.05,
    etaMinutes: 0,
    distanceKm: 0,
    direction: 120,
  },
  {
    id: "T-124",
    type: "fm",
    title: "FM เมืองใหม่ 89.75",
    province: "Chachoengsao",
    district: "Phanom Sarakham",
    status: "pending",
    ranking: null,
    lat: 13.7451,
    long: 101.3581,
    etaMinutes: 62,
    distanceKm: 38.2,
    freq: 89.75,
  },
  {
    id: "T-125",
    type: "interference",
    title: "AWN-301 · Sector D",
    province: "Chachoengsao",
    district: "Bang Khla",
    status: "pending",
    ranking: "major",
    lat: 13.722,
    long: 101.205,
    etaMinutes: 71,
    distanceKm: 44.1,
    direction: 310,
  },
];

export const SUMMARY_STATS = {
  totalTasks: 218,
  inspected: 147,
  pending: 58,
  critical: 13,
};

export const PROVINCES = ["All", "Chonburi", "Rayong", "Chachoengsao"] as const;
